# Generated by Django 6.1 on 2026-09-09 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_edu', models.CharField(choices=[('Elementary School', 'elementary school'), ('Junior High School', 'junior high school'), ('Senior High School', 'senior high school'), ("Bachelor's Degree", "bachelor's degree")], max_length=20)),
            ],
        ),
    ]
