# Generated by Django 6.1 on 2026-09-09 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_education_end_year_education_is_ongoing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='description',
            field=models.TextField(default=2013),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='education',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
    ]
