# Generated by Django 6.1 on 2026-09-09 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_education_description_education_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='skills',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
