# Generated by Django 6.1 on 2026-09-11 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_education_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='thumbnail',
            field=models.URLField(blank=True, null=True),
        ),
    ]
