# Generated by Django 6.1 on 2026-09-16 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_education_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='category_edu',
            field=models.CharField(choices=[('Elementary School', 'Elementary School'), ('Junior High School', 'Junior High School'), ('Senior High School', 'Senior High School'), ("Bachelor's Degree", "Bachelor's Degree")], max_length=20),
        ),
    ]
