# Generated by Django 6.1 on 2026-09-20 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_education_category_edu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='ended_at',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
