# Generated by Django 6.1 on 2026-09-20 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_experience_ended_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
