# Generated by Django 6.1 on 2026-10-03 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_education_starred_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='thumbnail',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
